### ISSUE TITLE
Limit mute commands to max time 1 day

### ISSUE THREAD

**Issue by ILiedAboutCake** [destinygg/chat-bot#60]
Chat mute commands in both dgg/twitch should be limited to 1 day in time, for example a command !mute 1024h RTBALOL should be rounded out to 24 hours.

**Comment by tbreslein** [comment]
As I told you two days ago, since this should be (in theory) pretty easy, I'm gonna tackle this (despite not having done JS in over a decade), but this is probably a good way to get to know the codebase.

Just two questions:
1) Do you want the chat message to still display the original parsed mute duration, to keep up the illusion, or do you want the message to actually say that the mute duration has been capped to 24h?

2) Do you want the cap to be set in the config? If so, would `PunishmentCache` be the appropriate place for that?

**Comment by ILiedAboutCake** [comment]
1. The bot should be posting the true amount of time the mute takes place. So if someone issues `!mute 7d mrmouton` the mute response should be `19:55  Bot: Muting: mrmouton for 1d`

2. After some thinking, I don't think mute limits should apply to Twitch chat. Dgg has options for timed bans, Twitch does not. Definitely make it configurable, `PunishmentCache ` is probably fine for now.

**Comment by shadedred** [comment]
https://github.com/destinygg/chat-bot/blob/master/lib/services/punishment-read-write-stream.js#L126 There's already a limit on mute duration, you can just make it configurable by injecting configuration into the punishment streams construction https://github.com/destinygg/chat-bot/blob/master/lib/services/service-index.js#L33
